name: Auto Assign

on:
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - opened
      - reopened

jobs:
  automate-project-columns:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/config_auto_assign.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
